### ISSUE TITLE
日期插件能否加入农历或提供扩展的接口？

### ISSUE THREAD

**Issue by liangei** [yued-fe/lulu#10]
如题？
再如希望在对应的日期加点备注或价格之类~~

**Comment by zhangxinxu** [comment]
可以考虑下~但lulu的设计理念其实是JS整合到项目中，自己根据需求，随便修改组件的CSS和JS，而不是为了应付各种场景把lulu中的JS变得又大又强。

**Comment by zhangxinxu** [comment]
目前已支持特殊日期标记，主要使用CSS自定义UI。效果如下图：

[https://qidian.qpic.cn/qidian_common/349573/401429076df08fde8ab99c7130d98baa/0](https://qidian.qpic.cn/qidian_common/349573/401429076df08fde8ab99c7130d98baa/0)

可参见文档“标记特殊的日子，例如国庆节，劳动节等”那里的演示。
