### ISSUE TITLE
关于时间日期选择器的功能补充

### ISSUE THREAD

**Issue by AGG-an** [yued-fe/lulu#100]
在现实开发中，会要求某一个输入框能同时选择日期与时间；
目前文档有支持到时间或者日期，但是组合起来的整体确没有；能不能再增加一个功能 使其能同时选择日期和时间呢？

**Comment by zhangxinxu** [comment]
@AGG-an 可以的，不过是提供组装使用案例，不会作为独立的组件发布，因为和LuLu UI的设计理念不符合。

**Comment by zhangxinxu** [comment]
@AGG-an Edge主题已新增 datetime-local 日期时间选择类型
