### ISSUE TITLE
【轻提示】功能建议

### ISSUE THREAD

**Issue by Zhuyh-vs** [yued-fe/lulu#102]
如在登录时，输入完账密信息，密码框被聚焦，敲击enter发送请求验证信息，此时密码框任聚焦，弹出信息后，如：“登录成功”、“密码错误”等，密码框会取消聚焦。望修复

**Comment by zhangxinxu** [comment]
好的，感谢反馈，我想下解决方法，因为提示信息出现聚焦也是符合交互的~

**Comment by zhangxinxu** [comment]
已修复，提示消失后，输入框会继续focus。或者在输入框或form元素上设置 keepfocus 属性，则焦点不会转移。目前只更新于Edge主题。
