### ISSUE TITLE
Pagination jquery3.3.1版本移除了.size()方法导致报错

### ISSUE THREAD

**Issue by mjt412885604** [yued-fe/lulu#14]
/**
     * 分页显示（也是刷新方法）
     * @return {Object} 返回当前实例
     */
    Pagination.prototype.show = function() {
        // 数据合法性处理
        var num = this.num;
        num.length = Math.max(num.length, 0);
        num.every = Math.max(num.every, 1);

        // current合法性处理
        var maxCurrent = Math.ceil(num.length / num.every);
        if (num.current > maxCurrent) {
            num.current = maxCurrent;
        }

        num.current = Math.max(num.current, 1);

        if (this.el && this.el.container && this.el.container.size()) {
            // 分页刷新
            this.el.container.html(this.create(num, this.mode));
        }

        return this;
    };

**jquery3.x移除了size方法，建议作者修改一下源码**

**Comment by zhangxinxu** [comment]
感谢反馈，已修改！
