### ISSUE TITLE
第一条：有没有上传文件或者图片组件

### ISSUE THREAD

**Issue by zuoyifeng** [yued-fe/lulu#2]
大神，有没有上传组件，比如图片和文件;
还有，有没有支持表格数据操作的组件这个运用挺广的，

**Comment by zhangxinxu** [comment]
1. 没有上传组件，但在表单验证那里有上传交互示意。LuLu UI要兼容IE8，非flash方案只能单图，无刷新要走iframe，会比较啰嗦，加上LuLu UI主要用来解决UI问题，上传组件的UI目前LuLu UI已经能够满足，因此推荐使用已有成熟技术方案 + LuLu UI的UI。
2. 有表格操作，参见富交互列表，局部模板。如果您的项目有非常多的数据操作，推荐使用antDesign这类面向中后台的UI框架。
