### ISSUE TITLE
前端小白问：如何全部打包dist

### ISSUE THREAD

**Issue by Zsoner** [yued-fe/lulu#25]
我就喜欢一起撸，但貌似简单的合并会报依赖错误
`gulp.task('Min', function(done) {
    gulp.src([path.js+'/common/ui/*',path.js+'/common/comp/*'])
        .pipe(concat('main.js')) 
        .pipe(gulp.dest(path.dist))
        .pipe(rename({
            suffix: '.min'
        }))
        .pipe(uglify())
        .pipe(gulp.dest(path.dist))
        .on('end', done);
});
`

**Comment by zhangxinxu** [comment]
顺序问题。
Keyboard.js, Enhance.js, Follow.js, 然后...，如果报依赖错误，缺哪个就把哪个放在前面先合并就好了。
