### ISSUE TITLE
表单验证问题：校验成功后的回调里面提交表单报错

### ISSUE THREAD

**Issue by wuchongzi** [yued-fe/lulu#26]
[复现地址](https://jsfiddle.net/debugger/t2n1p4yv/)

控制台报错：
```
Maximum call stack size exceeded
```
循环调用堆栈溢出？那么我该怎么去以form方式去提交表单

**Comment by wuchongzi** [comment]
还有这里在onSuccess的回调会执行多次
```
new Validate($('form'), function() {}, {
	onSuccess: function() {
		console.log(1)
	}
})
```

**Comment by zhangxinxu** [comment]
new Validate($('form'), function() {
    // 下面这句造成的问题，死循环了
    _$('form').submit();_
});

表单验证本身走的就是submit事件，目前LuLu UI是全ajax表单提交设计。

我这边加一句话支持验证成功后原生表单提交，稍等……

**Comment by zhangxinxu** [comment]
下载最新的Validate.js，然后使用示意如下：
new Validate($('form'), function (validate) {
    **validate.stopValidate = true;**
    this.submit();
});

效果和使用可参见文档Part1.7 验证成功后走原生提交。

**Comment by wuchongzi** [comment]
好的，赞一下！
