### ISSUE TITLE
表格上checkbox的问题

### ISSUE THREAD

**Issue by Zsoner** [yued-fe/lulu#28]
![image](https://user-images.githubusercontent.com/11805413/43120394-9f01f472-8f4c-11e8-8b37-8bee1e77eadb.png)
每次我在空白的地方点击时，js会触发checkbox,两个会同时变化

**Comment by zhangxinxu** [comment]
好的，我知道什么原因了，我处理下~

**Comment by zhangxinxu** [comment]
感谢反馈，已修！只对第一个<td>的checkbox处理
