### ISSUE TITLE
iframe内弹框测试 

### ISSUE THREAD

**Issue by mablevi** [yued-fe/lulu#31]
mac v10.13.6
chrome v70.0

点击按钮没有任何反应
![image](https://user-images.githubusercontent.com/6835617/44436174-590ebf80-a5e6-11e8-87a6-b0addc5b998b.png)

**Comment by zhangxinxu** [comment]
你好，此页面需要http/https协议打开，因为静态资源自动缺省了协议头，你看看是不是这个原因？

**Comment by zhangxinxu** [comment]
文档已写死https协议，支持直接双击打开预览。
