### ISSUE TITLE
checkbox实现的疑问

### ISSUE THREAD

**Issue by tenstep** [yued-fe/lulu#33]
`.ui-checkbox{
  ...
  border: 1px solid rgba(0, 0, 0, 0);
  border-radius: 4px;
  box-sizing: border-box;
  box-shadow: inset 0 1px, inset 1px 0, inset -1px 0, inset 0 -1px;
  ...
}`
为什么不直接使用border，而是隐藏border，使用内阴影来模拟checkbox边框，是基于什么考虑吗，望解惑

**Comment by zhangxinxu** [comment]
点击的尺寸更大，体验会更好，希望可以帮你解惑。
