### ISSUE TITLE
您好，Select组件 options属性设置disabled无效果

### ISSUE THREAD

**Issue by tianshuoQAQ** [yued-fe/lulu#34]
我按照 [官网demo](https://l-ui.com/single/apis/select.html)在本地Chrome下打开网页发现Select组件的options属性设置disabled无效果。是不是需要加额外的处理？
![1](https://user-images.githubusercontent.com/42518720/45269274-a089bc80-b4bd-11e8-8983-b6c4834644cc.png)
![2](https://user-images.githubusercontent.com/42518720/45269275-a089bc80-b4bd-11e8-9e06-b8cd45d22394.png)

**Comment by zhangxinxu** [comment]
好的，感谢反馈。

**Comment by zhangxinxu** [comment]
单独Select演示页面，没有设置全局的disabled类名，已更新。
