### ISSUE TITLE
请问弹窗组件怎么设置才能在同一个页面只允许同时出现一个？

### ISSUE THREAD

**Issue by zhoushiya** [yued-fe/lulu#4]
现在遇到的情况是我做登录和注册两个弹窗，但是很奇怪，如果我重复点击5次弹出登录窗口再关闭的话，只要点击注册窗口就会一次性弹出5个注册窗口。所以想问问怎么才能永远只允许存在一个弹窗？

**Comment by zhangxinxu** [comment]
应该是你的点击事件重复绑定了。请检查下自己代码。

**Comment by zhangxinxu** [comment]
如果你弹框内元素是以DOM方式加载，则再次点击时候不需要在new Dialog()，直接之前的弹框实例show()就好了。示意如下：

`var registDialog;

$().on('click', function () {
   if (registDialog) {
    registDialog.show();
  } else {
    registDialog = new Dialog(/*...*/);
  }
});`
