### ISSUE TITLE
文档css完整引入错误

### ISSUE THREAD

**Issue by Valar103769** [yued-fe/lulu#40]
发布与使用中给的在线资源完整引入链接不对，不能完整渲染form组件的示例html结构，每个html到底需要什么css以及js，建议在页面html示例顶部粘贴

**Comment by Valar103769** [comment]
鑫哥，强烈强烈建议lulu ui也应该出一个集合的压缩版与未压缩版.css,以及.js，包含进Form以及Table里，
原因一： 考虑到现在很多中小公司不考虑按需加载，比如有时候只用到一次的swiper也为了方便完整引入；
原因二： lulu ui每个css以及js都存在文件依赖关系，并不适合按需引入。
原因三： 也是最重要的，越简单越好，可以简单到直接像其他大型ui框架一样放上html模板，css模板，js模板；
额外提个issue，建议在示例里取消*符号，比如
···css
<link rel="stylesheet" href="//qidian.gtimg.com/lulu/theme/peak/css/common/ui/*.css">
···
因为*在js中算关键词，比如import * as from ‘xxx.js’ 用在lulu ui文档手册中我觉得会有误解
望采纳

**Comment by zhangxinxu** [comment]
已增加 all.js
https://github.com/yued-fe/lulu/blob/master/theme/peak/js/common/all.js

**Comment by cooper1x** [comment]
@Valar103769 LULU没有Swiper吧？

**Comment by zhangxinxu** [comment]
> @Valar103769 LULU没有Swiper吧？

没有，暂时没有增加的计划。
