### ISSUE TITLE
luluui 对jq版本有要求嘛？具体使用哪个版本的jqery？

### ISSUE THREAD

**Issue by zmzxn** [yued-fe/lulu#41]
luluUI 对jq的版本有要求嘛？

**Comment by zhangxinxu** [comment]
基于1.9.*开发，高版本应该也支持。

**Comment by zmzxn** [comment]
> 基于1.9.*开发，高版本应该也支持。

感谢鑫哥，这么快做出回复，谢谢，正在学习使用这个UI，有问题还需要多多咨询鑫哥！
