### ISSUE TITLE
表单验证错误提示信息会跟随页面滚动而滑动是怎么回事？

### ISSUE THREAD

**Issue by zmzxn** [yued-fe/lulu#42]
![image](https://user-images.githubusercontent.com/23032786/55676990-4f865d80-5912-11e9-9164-514fb09db3b3.png)
我不知道如何解决了，还望指点一下

**Comment by zhangxinxu** [comment]
因为Tips提示创建是在body元素下，你这个页面的滚动应该是普通div元素，因此导致tips不会随着滚动。可以试试改变下布局，滚动还是<html>滚动，左侧固定使用fixed定位。
