### ISSUE TITLE
Dialog希望增加嵌套iframe

### ISSUE THREAD

**Issue by Zsoner** [yued-fe/lulu#43]
如题

**Comment by zhangxinxu** [comment]
具体描述下，可以嵌套iframe，里面直接content直接`'<iframe></iframe>'`不行吗？

**Comment by Zsoner** [comment]
嗯，最终原理差不多,但希望能简化  类似layer 里面content传 url地址即可

**Comment by zhangxinxu** [comment]
恩，下个版本可以考虑下。
