### ISSUE TITLE
Pagination.show()方法不生效

### ISSUE THREAD

**Issue by smallxiaotongxue** [yued-fe/lulu#46]
page.num.length = 15;
page.show();

page为pagination实例

this.el.container.html(this.create(e, this.mode)) 好像这一句代码渲染不出来

**Comment by smallxiaotongxue** [comment]
麻烦大佬看下是为什么呢？

**Comment by zhangxinxu** [comment]
有demo吗？

**Comment by smallxiaotongxue** [comment]
var Pagination = new Pagination($('#pagination'), {
  length: 0,
  current: 1,
  every: 10
});

$.ajax({
 ...
success: function (data) {
  Pagination.num.length = data.total; // 15
  Pagination.show();
}
});

大概就是这个样子，点击按钮，异步请求后，调用show方法失效，麻烦鑫旭大神看下，谢谢!

**Comment by 9raxdev** [comment]
顺便提一下，富交互列表这里，遇到表格数据有图片，数据量较多时计算高度有问题
![image](https://user-images.githubusercontent.com/11805413/58926394-aa56fc80-877d-11e9-8fdc-dc1dbecf8e6c.png)导致分页被拦截，实际的表格table-size高度大于计算的

具体比较
![image](https://user-images.githubusercontent.com/11805413/58926466-face5a00-877d-11e9-869e-55e55076a2dd.png)
![image](https://user-images.githubusercontent.com/11805413/58926496-176a9200-877e-11e9-9d72-48aadab7ed18.png)

**Comment by 9raxdev** [comment]
最后一张图我实际拉到底也不会显示，他实际实在table列表下面，高度在表格中靠下左右，z-index 遮住了

**Comment by zhangxinxu** [comment]
> Pagination

Pagination这个变量命名不行的吧

**Comment by zhangxinxu** [comment]
> 顺便提一下，富交互列表这里，遇到表格数据有图片，数据量较多时计算高度有问题
> ![image](https://user-images.githubusercontent.com/11805413/58926394-aa56fc80-877d-11e9-8fdc-dc1dbecf8e6c.png)导致分页被拦截，实际的表格table-size高度大于计算的
> 
> 具体比较
> ![image](https://user-images.githubusercontent.com/11805413/58926466-face5a00-877d-11e9-869e-55e55076a2dd.png)
> ![image](https://user-images.githubusercontent.com/11805413/58926496-176a9200-877e-11e9-9d72-48aadab7ed18.png)

因为图片高度没有设置，图片异步加载，导致数据载入后计算的高度并不是最终的高度。可以在.table-size元素上设置data-animation="0"，Table.js预留了这个后门，可以关掉动画。

**Comment by 9raxdev** [comment]
收到！

**Comment by 9raxdev** [comment]
> > 顺便提一下，富交互列表这里，遇到表格数据有图片，数据量较多时计算高度有问题
> > ![image](https://user-images.githubusercontent.com/11805413/58926394-aa56fc80-877d-11e9-8fdc-dc1dbecf8e6c.png)导致分页被拦截，实际的表格table-size高度大于计算的
> > 具体比较
> > ![image](https://user-images.githubusercontent.com/11805413/58926466-face5a00-877d-11e9-869e-55e55076a2dd.png)
> > ![image](https://user-images.githubusercontent.com/11805413/58926496-176a9200-877e-11e9-9d72-48aadab7ed18.png)
> 
> 因为图片高度没有设置，图片异步加载，导致数据载入后计算的高度并不是最终的高度。可以在.table-size元素上设置data-animation="0"，Table.js预留了这个后门，可以关掉动画。

收到！
