### ISSUE TITLE
IE 11下 select 下拉框兼容性问题 

### ISSUE THREAD

**Issue by junior-yang** [yued-fe/lulu#47]
在 IE11 下开启 Edge 模式，对 select option 设置的 height、min-height、padding 等 CSS 属性都不起作用，导致原始 option 选项的位置与生成的选项位置不匹配，选择选项的时候会发生错乱。

**Comment by zhangxinxu** [comment]
无法复现，IE11默认不就是Edge吗？option 设置的 height、min-height、padding确实浏览器不支持，尝试设置在select元素上。不清楚你说的是什么意思？你指多选吗？

**Comment by junior-yang** [comment]
IE11默认是Edge，在多选的 select 元素上设置了高度，实际的 option 元素上设置的 min-height、height、padding 浏览器是不支持，所以实际的单个 option 高度和 ui-select 下单个 ui-select-datalist-li 元素高度不一致

**Comment by junior-yang** [comment]
ui.css 中下面这段不起作用
select[multiple] > option {
  min-height: 38px;
  height: 38px;
  padding: 0; }

**Comment by zhangxinxu** [comment]
IE edge是使用font-size:calc(34px - 1px)控制的。你看看是不是被重置了。

**Comment by junior-yang** [comment]
感恩，在IE edge 下，option 从 select[multiple] 继承而来的 font-size 被 * { font-size: 12px } 覆盖了，cascading style sheets
