### ISSUE TITLE
关于switch的实现

### ISSUE THREAD

**Issue by Seasonley** [yued-fe/lulu#48]
我看了几种不同的switch实现方式，lulu是用原生checkbox的，ant design是用button的。然后又看了[a11y_styled_form_controls](https://scottaohara.github.io/a11y_styled_form_controls/#switches--toggle-buttons) 和 [inclusive-components.design](https://inclusive-components.design/toggle-button/)的示例，感觉`<button role="switch" aria-checked="true"></button>`是最符合语义的。查了[w3c](https://www.w3.org/TR/wai-aria/#switch) 也没明确说最佳实践，你们是怎么考虑的？

**Comment by zhangxinxu** [comment]
No JS
