### ISSUE TITLE
建议完善几个核心组件,数据表格,左侧导航,顶部tab

### ISSUE THREAD

**Issue by di3663** [yued-fe/lulu#49]
基础组件美化的太多了,但是大部分可用性不佳,因为没有这些核心组件

layui这种就是抓住了这几个点,其实layui的界面甚至都算不上好看,js部分也很差

**Comment by di3663** [comment]
像分页这种拼几个按钮就行,用处不大

**Comment by zhangxinxu** [comment]
感谢你的建议与反馈。
