### ISSUE TITLE
[bug]button的loading()方法生效时,整个button高度变成18px

### ISSUE THREAD

**Issue by Valar103769** [yued-fe/lulu#50]

**Comment by Valar103769** [comment]
我是用的是div模拟的button, outline依然存在

**Comment by Valar103769** [comment]
unloading()有问题, isLoading()返回false, 但loading效果依然在, div模拟的按钮

**Comment by Valar103769** [comment]
我换成a便签模拟unloading()生效了

**Comment by zhangxinxu** [comment]
div模拟按钮只有形，功能并未支持，如果希望div 模拟按钮的loading检测也有效果，可以在Loading.js中，几处container.is('a,label,input,button')语句增加div，例如container.is('a,label,input,button,div')。
你的反馈很有价值，在下一个主题开发时候会考虑你这种场景的。
