### ISSUE TITLE
如果定位为pc网页端UI，建议加上幻灯片、下拉菜单等组件

### ISSUE THREAD

**Issue by roywu888** [yued-fe/lulu#51]
如果定位为pc网页端UI，建议加上幻灯片、下拉菜单等组件，这样就比较齐全了。

**Comment by zhangxinxu** [comment]
下拉菜单，可以参考 Select，DropList以及Datalist 这些。幻灯片可以下一个版本加上。

**Comment by roywu888** [comment]
好的。谢谢你的回复！




------------------ 原始邮件 ------------------
发件人: "zhangxinxu"<notifications@github.com>;
发送时间: 2019年7月8日(星期一) 下午2:41
收件人: "yued-fe/lulu"<lulu@noreply.github.com>;
抄送: "骨头"<596750766@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [yued-fe/lulu] 如果定位为pc网页端UI，建议加上幻灯片、下拉菜单等组件 (#51)




下拉菜单，可以参考 Select，DropList以及Datalist 这些。幻灯片可以下一个版本加上。
