### ISSUE TITLE
希望在switch上面增加值映射

### ISSUE THREAD

**Issue by 9raxdev** [yued-fe/lulu#55]
由于是基于checkbox,目前switch在开的状态可以在表单提交的时候附带on过去，如果关闭状态就什么也没有，希望增加映射，动态改变checkbox的值 ，比方开是1 关是-1  可以自定义。

也就是想switch拥有radio的功能

**Comment by zhangxinxu** [comment]
感谢反馈，这个我需要斟酌一下。
