### ISSUE TITLE
捕获小bug一枚

### ISSUE THREAD

**Issue by 9raxdev** [yued-fe/lulu#56]
![image](https://user-images.githubusercontent.com/11805413/62189884-b7215680-b3a2-11e9-9858-7f611c836f20.png)
触发场景：name 名带有数组结构，比如
![image](https://user-images.githubusercontent.com/11805413/62189983-e46e0480-b3a2-11e9-8cd0-159ee9e0afde.png)
原因是：没有加引号
![image](https://user-images.githubusercontent.com/11805413/62190030-f8196b00-b3a2-11e9-9303-fcad1c889ad2.png)

**Comment by zhangxinxu** [comment]
好的，感谢反馈！
