### ISSUE TITLE
不能和wordpress的jquery搭配使用，估计和这个$符有关

### ISSUE THREAD

**Issue by freehzw** [yued-fe/lulu#59]
当然用官方的jquery文件是没问题的，但因为是在WP下使用，打算还是用WP内置的jquery。
浏览器报错：

`all.js:505 Uncaught TypeError: Cannot read property 'fn' of undefined
    at all.js:505
    at all.js:485
    at all.js:487`

WP的jQuery是 v1.12.4。这个要怎么处理啊？

**Comment by zhangxinxu** [comment]
顺序有关，all.js请在jquery.js位置的后面。
