### ISSUE TITLE
select在没有option的情况下$('select').selectMatch();会报错

### ISSUE THREAD

**Issue by 9raxdev** [yued-fe/lulu#60]
![image](https://user-images.githubusercontent.com/11805413/62689900-401d3b00-b9fe-11e9-852c-e6ffde029683.png)
![image](https://user-images.githubusercontent.com/11805413/62689929-4f9c8400-b9fe-11e9-9626-3a3258f2e921.png)

触发场景：页面存在多个select ,部分option是从数据库提取，要新增后才有，当遇到没有的情况下会报错

**Comment by zhangxinxu** [comment]
好的，感谢反馈~
