### ISSUE TITLE
LULU  Figma 设计文件 bug 反馈

### ISSUE THREAD

**Issue by ziven27** [yued-fe/lulu#63]
## 使用方法

[点我下载 ](https://github.com/yued-fe/lulu/raw/master/LULU-UI-Figma.fig) LULU UI Figma 源文件。
然后打开 Figma 客户端或者浏览器打开 Figma ，然后拖如源文件即可。

![image](https://user-images.githubusercontent.com/7261176/70146038-58674300-16dc-11ea-9f22-4647504573b3.png)

**Comment by LifeIsACat** [comment]
请问，在使用modern版本时，缺少all.js文件，有什么替代方案吗

**Comment by ziven27** [comment]
> 请问，在使用modern版本时，缺少all.js文件，有什么替代方案吗

![image](https://user-images.githubusercontent.com/7261176/82036964-19e6a300-96d4-11ea-87fc-f9ee130b9bd7.png)

缺少 all.js 引用一下？

**Comment by zhangxinxu** [comment]
> 请问，在使用modern版本时，缺少all.js文件，有什么替代方案吗

建议新开issues提这个问题，modern版本all.js我已经合并好了，参见：https://github.com/yued-fe/lulu/tree/master/theme/modern/js/common

**Comment by lindiors** [comment]
选项卡切换效果失效

**Comment by ziven27** [comment]
> 选项卡切换效果失效

这个失效的是哪个版本的哪个地址呢？

**Comment by jiao2563719877** [comment]
考虑加一个文本按钮吗

**Comment by zhangxinxu** [comment]
> 考虑加一个文本按钮吗

可以，这周处理下
