### ISSUE TITLE
【Dialog模态层弹框】引入文档示例报错

### ISSUE THREAD

**Issue by cooper1x** [yued-fe/lulu#67]
![image](https://user-images.githubusercontent.com/9080789/72342449-66f74000-3707-11ea-9a99-a6ba3ca6e8b7.png)
复制粘贴到本地demo，发现出现红色报错append报错。

**Comment by zhangxinxu** [comment]
是不是file协议访问的？我自己测试并没有此问题。看来有必要把文档协议头都改成https~
