### ISSUE TITLE
apis.dialog示例bug反馈

### ISSUE THREAD

**Issue by inwikipedia** [yued-fe/lulu#68]
https://l-ui.com/pure/apis.dialog.html
![image](https://user-images.githubusercontent.com/644260/75135240-e707c100-571b-11ea-8092-09179701f102.png)
双击/多次快速点击按钮之后,esc不能关闭

**Comment by BrucePhoebus** [comment]
需要聚焦中心块才能按esc关闭，不知道是不是设计成这样的，貌似没有必要

**Comment by zhangxinxu** [comment]
感谢反馈，明天优化下。

**Comment by zhangxinxu** [comment]
已优化完毕。
