### ISSUE TITLE
Pure主题官网Textarea文档字符错误

### ISSUE THREAD

**Issue by ck18781145809** [yued-fe/lulu#69]
![C3CA5B7E-ED28-4aef-850D-38BAF6E56D60](https://user-images.githubusercontent.com/23161385/75851638-270a2a80-5e25-11ea-9dd8-25ba46357bd3.png)

![59BCFD29-7B8F-47e6-919B-282C9C68F4CB](https://user-images.githubusercontent.com/23161385/75851761-7a7c7880-5e25-11ea-88cc-497db58d88f3.png)

【[普通文本域](https://l-ui.com/pure/apis.textarea.html)】 代码块出现

**Comment by zhangxinxu** [comment]
感谢反馈，已修复。
