### ISSUE TITLE
希望增加表格列冻结功能

### ISSUE THREAD

**Issue by 9raxdev** [yued-fe/lulu#73]
如题,目前遇到的情况是，如果列比较多，ui-table  table-layout: fixed; 时数据会重叠，如果 table-layout: auto; 数据又会超出父元素 

![image](https://user-images.githubusercontent.com/11805413/79941281-889a5d00-8496-11ea-871d-e33f9def51e2.png)

希望有冻结功能，冻结也能优化手机体验

**Comment by zhangxinxu** [comment]
感谢反馈，此功能添加后，对组件带来的负担大于收益，目前不会加入组件本身，可以作为第3方案例加入在文档中，欢迎贡献插件代码。
