### ISSUE TITLE
chrome默认填表 这个问题还是要考虑下

### ISSUE THREAD

**Issue by lifetin** [yued-fe/lulu#74]
![11](https://user-images.githubusercontent.com/10474968/82897824-cf461000-9f8a-11ea-9a8f-1d64ce8d8321.png)

点击就弹出来默认的.盖住了这个

**Comment by zhangxinxu** [comment]
奇怪，这里设置了autocomplete="off"，照理来说不会触发Chrome的自动填充的呀？

**Comment by zhangxinxu** [comment]
已处理。
