### ISSUE TITLE
框架针对的是网站类框架-有经典的网站模板？

### ISSUE THREAD

**Issue by softsrc** [yued-fe/lulu#80]
框架的定位很清晰，且目前确实缺少这类简洁，轻量级的框架，如果能提供几个比较的经典的网站模板一定会流行起来
原因:
     1. 中小公司没有自己的设计师，往往前端的能力也不是很高，通常就是修修改改类的工作
     2. Vue 之所以火起来很大程度是因为有了elementui以及 默认实现的admin ui

**Comment by softsrc** [comment]
另外建议增加用户反馈通道  qq ，微信， 论坛等都可以
多数用户还是很在意社区活跃度的，希望建立用户反馈通道，互动起来，给使用者注入更多的确定性

**Comment by zhangxinxu** [comment]
都是很好的建议，我们也有类似的想法，不过团队业务发展迅速，常年处于招人不满状态，并没有多余人力做这方面的工作，不知道有没有兴趣投递下简历，zhangxinxu@zhangxinxu.com，或者有最近看机会的同事、朋友，也可以帮忙推荐。
