### ISSUE TITLE
关于禁用按钮以及文本框等鼠标样式

### ISSUE THREAD

**Issue by btea** [yued-fe/lulu#83]
对于禁用按钮以及输入框等，鼠标的样式设置为 `not-allowed` 是不是更友好一些。

**Comment by zhangxinxu** [comment]
不是的哟，not-allowed其实是不准确的用法，通常表示交互中的行为的禁止，例如拖拽释放无效，default才是正确的语义表示，你应该取其他的项目中反馈，禁用按钮应该是 default。因为，虽然按钮禁用，但是某些行为还是保持的，例如，我们可以显示 title 信息等。
LuLu UI 遵循标准交互规范，和浏览器原生规则保持一致。
