### ISSUE TITLE
Select下拉框在弹窗内使用会撑开容器高度

### ISSUE THREAD

**Issue by cdswyda** [yued-fe/lulu#86]
![2021-11-03](https://user-images.githubusercontent.com/13060680/140050903-91511070-00de-4c3e-b51a-447d8a2798e8.gif)

**Comment by zhangxinxu** [comment]
外部容器的 overflow:auto 去掉有什么影响么？

**Comment by qiutian00** [comment]
弹框里面内容高度稍微大一点么？ 避免突然出现滚动条

**Comment by cdswyda** [comment]
> 外部容器的 overflow:auto 去掉有什么影响么？

似乎不能去掉，这个场景需要能新增很多行，有可能需要超出弹窗高度，因此有内部滚动。

这个场景比较特殊，个人是改了下源码，扩展了个 `append-to-body` 属性。

lulu 是否考虑此场景，若考虑可以新增PR。

**Comment by zhangxinxu** [comment]
@cdswyda  感谢反馈，欢迎 pr，不会属性名称可能需要微调下，例如使用 data-sibling="false" 。

**Comment by zhangxinxu** [comment]
Pure 主题已经改成 body append，Edge  主题使用 data-sibling="false" 设置。
