### ISSUE TITLE
关于lulu

### ISSUE THREAD

**Issue by wsyxl365** [yued-fe/lulu#89]
张老师您好，一直有关注您css方面的学习，这次可以用上你们开发的UI组件库也非常高兴。
关于lulu我有一点想问下，是否我可以专注于用vue或者react做纯功能或者业务组件的开发，在最终完成后使用lulu UI 作为组件库的皮肤或者外观修饰，真正做到UI不随着技术栈的变化而变化，解耦分离的效果。

**Comment by zhangxinxu** [comment]
为何要完成后再使用呢？因为我不知道你 Vue 或 React 具体的实现，所以不清楚，通常 Vue 或 React 组件，UI 和功能是深度绑定的，我不太确定你能否剥离。
如果只是纯 UI 变化，LuLu UI 是可以的，尤其是静态组件和大多数的基于原生控件构建的组件。

**Comment by wsyxl365** [comment]
> 

感谢张老师回答，我大概明白意思了 我再去构思构思 一定把lulu UI 用到自己的组件库中 ~。~

**Comment by qiutian00** [comment]
好像ui会变化很快，需求可能一下要改交互方式等， 最后还是得动代码 (找一个适合项目的场景，api灵活)

**Comment by wsyxl365** [comment]
> 好像ui会变化很快，需求可能一下要改交互方式等， 最后还是得动代码 (找一个适合项目的场景，api灵活)

是的 我想的还是简单了  只想我最终vnode生成的是不绑定Class的div span等，但是实际开发中确实UI和功能绑定比较深
