### ISSUE TITLE
关于select下拉框的小建议

### ISSUE THREAD

**Issue by talenHuang** [yued-fe/lulu#9]
### 这儿的箭头是否应该有个动画更合理一点？
![image](https://user-images.githubusercontent.com/22046308/41770956-38cf80d0-7646-11e8-8960-a3debbb91bda.png)

**Comment by zhangxinxu** [comment]
如果你觉得这里应该有动画，可以在使用的时候自己加下。lulu ui这里的下拉框本意设计是让原生下拉框UI变漂亮，因此交互行为设计上和原生<select>保持一致。
