### ISSUE TITLE
计数器文本域不生效

### ISSUE THREAD

**Issue by MrXujiang** [yued-fe/lulu#90]
带计数器的文本域没有随着文本增多而变化，具体demo：https://l-ui.com/edge/apis.textarea.html

**Comment by yvoune** [comment]
你好，我已收到您的重要信息，我会尽快查看的！

**Comment by zhangxinxu** [comment]
这里其实只是静态展示，好吧，这个问题很多人提，我处理下，现在应该好了。

**Comment by MrXujiang** [comment]
持续推进
