### ISSUE TITLE
建议把网站https下了

### ISSUE THREAD

**Issue by yjw0628** [yued-fe/lulu#93]
lulu-ui 支持ie8 ,官网却无法在ie8下打开, 岂不是很尴尬

因为  Let's Encrypt 的 https证书无法在 ie8下使用

至少支持双协议,不做强制跳转吧

**Comment by yjw0628** [comment]
![image](https://user-images.githubusercontent.com/15664734/150319810-41092e99-5f79-407c-b21a-be3487228c8e.png)

**Comment by zhangxinxu** [comment]
感谢反馈，https://l-ui.com 使用的是 GitHub 托管，证书或者调整我这边无法控制，你可以访问国内托管的地址：
https://www.zhangxinxu.com/sp/lulu/mockup/single/apis/datetime.php

然后我在文档中示意下。
