### ISSUE TITLE
直接引用all.js会发生报错Uncaught TypeError: Cannot read properties of null (reading 'get')

### ISSUE THREAD

**Issue by evilucifero** [yued-fe/lulu#94]
https://github.com/yued-fe/lulu/blob/efa211e61bdc551a124760ee8136c81212c5a61e/theme/edge/js/common/all.js#L1442

![截屏2022-02-11 18 05 38](https://user-images.githubusercontent.com/3679062/153572702-bfbb23e4-00f4-4d1d-b9c2-685e5c0ba638.png)

Chrome Version 99.0.4826.0 (正式版本) canary (x86_64)

**Comment by yvoune** [comment]
你好，我已收到您的重要信息，我会尽快查看的！

**Comment by zhangxinxu** [comment]
已关注，暂时未能复现，有没有可能是 customElements 对象在什么地方被重置了？

**Comment by evilucifero** [comment]
@zhangxinxu 我定位到了，主要问题是我这里的应用场景在chrome插件，注入的ContentScript受沙箱机制限制不能正常使用window……

**Comment by evilucifero** [comment]
这个问题主要出自我自己这边，我先自己想办法解决看看吧，感谢大佬关注。

**Comment by zhangxinxu** [comment]
@evilucifero 帮忙看下如果是 self.customElements 还会不会报错~

**Comment by evilucifero** [comment]
我直接调试节目看了一下，似乎从self里取到的Window是很纯净的Window对象，不含Web Component的这些API的，根因我还没一下子找到相关资料。不知道是不是我Chrome Extension的CSP写法问题

![截屏2022-02-14 17 18 23](https://user-images.githubusercontent.com/3679062/153835706-bab30fa6-d113-46c9-8dc5-f0e661ab2021.png)

**Comment by evilucifero** [comment]
@zhangxinxu Hi，看起来这个问题是个历史悠久的问题了，在Chromium论坛里找到一篇帖子 从14年至今一直有人在反馈这个问题，似乎除了引入额外的webcomponent polyfill以外暂时没有更好的解法。我这里的后续也就是暂时不在Chrome Extension开发里尝试使用了。希望这些信息能给你一些帮助。

传送门在此：https://bugs.chromium.org/p/chromium/issues/detail?id=390807

**Comment by zhangxinxu** [comment]
感谢您的反馈！❤
