### ISSUE TITLE
lu2不支持vue2吗？

### ISSUE THREAD

**Issue by liwuming** [yued-fe/lulu#97]
我在vue2.6.11中按照文档操作，始终报错，在vue3中正常，难道lu2不支持vue2吗？

**Comment by zhangxinxu** [comment]
是 Edge 主题吗？可否代码和报错截图示意下？

**Comment by liwuming** [comment]
是Edge主题，在vue3下正常，但是由于兼容性必须使用vue2，但是在vue2，一直无法识别ui-select组件

**Comment by zhangxinxu** [comment]
@liwuming 需要配置下，因为不是在Vue中注册的自定义组件。详见教程说明：https://www.zhangxinxu.com/sp/lulu/guide/edge/vue.html#:~:text=%E4%BB%B6%E5%9C%A8%20Vue-,%E4%B8%AD%E4%BC%9A%E5%8F%91%E7%94%9F%E8%AD%A6%E5%91%8A%EF%BC%8C%E9%9C%80%E8%A6%81%E5%A4%A7%E5%AE%B6%E9%85%8D%E7%BD%AE%E4%B8%8B,-%E3%80%82
<img width="814" alt="image" src="https://user-images.githubusercontent.com/496048/180115474-02d07a84-d815-4e20-ac0e-e267eb9043e7.png">

**Comment by liwuming** [comment]
谢谢
